modLoader="javafml"
loaderVersion="[31,)" 
[[mods]] #mandatory
modId="honkaiimpact"
version="${file.jarVersion}" 
displayName="HonkaiImpact3"
authors="ExtraMeteorP"
description='''
none
'''

[[dependencies.honkaiimpact]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0,)"
    ordering="AFTER"
    side="BOTH"